//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elektrika
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cena
    {
        public int CenID { get; set; }
        public Nullable<System.DateTime> CenOd { get; set; }
        public Nullable<System.DateTime> CenDo { get; set; }
        public Nullable<float> CenMala { get; set; }
        public Nullable<float> CenVisoka { get; set; }
    }
}
